### ISSUE TITLE
LibCore.Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Keyset does not exist при попытке подписания сертификатом из LocalMachine

### ISSUE THREAD

**Issue by kae** [CryptoPro/libcore#14]
Сертификат получается приведённым ниже кодом (Windows Server 2022, .NET 6.0.16)

Версия пакета `<PackageVersion Include="LibCore.Windows" Version="2023.3.16.1" />`

```csharp
	private static readonly ConcurrentDictionary<string, X509Certificate2> certCache = new(StringComparer.OrdinalIgnoreCase);
	private static X509Certificate2? GetSignerCert(string thumbprint, StoreLocation location) {
		if (certCache.TryGetValue(thumbprint, out var cert)) {
			return cert;
		} else {
			using var certStore = new X509Store(StoreName.My, location);
			certStore.Open(OpenFlags.ReadOnly);
			var certs = certStore.Certificates.Find(X509FindType.FindByThumbprint, thumbprint, false);
			if (certs.Count is 0) {
				return null;
			} else {
				cert = certs[0];
				_ = certCache.TryAdd(thumbprint, cert);
				return cert;
			}
		}
	}
```

Если сертификат получен из CurrentUser использование сертификата происходит успешно.

Если сертификат получен из LocalMachine, то несмотря на HasPrivateKey = true при попытке осуществления подписания получаю

```
     LibCore.Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Keyset does not exist
         at LibCore.Internal.NativeCrypto.CapiHelper.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
         at LibCore.Security.Cryptography.Gost3410_2012_256CryptoServiceProvider.get_SafeProvHandle()
         at LibCore.Security.Cryptography.Gost3410_2012_256CryptoServiceProvider.get_SafeKeyHandle()
         at LibCore.Security.Cryptography.Gost3410_2012_256CryptoServiceProvider.GetKeyPair()
         at LibCore.Security.Cryptography.Gost3410_2012_256CryptoServiceProvider..ctor(CspParameters parameters)
         at Internal.Cryptography.Pal.Windows.PkcsPalWindows.GetPrivateKey[T](X509Certificate2 certificate, Boolean silent, Boolean preferNCrypt)
         at Internal.Cryptography.Pal.Windows.PkcsPalWindows.GetPrivateKeyForSigning[T](X509Certificate2 certificate, Boolean silent)
         at LibCore.Security.Cryptography.GostCmsSignature.Gost2012_256CmsSignature.Sign(ReadOnlySpan`1 dataHash, HashAlgorithmName hashAlgorithmName, X509Certificate2 certificate, AsymmetricAlgorithm key, Boolean silent, String& signatureAlgorithm, Byte[]& signatureValue)
         at LibCore.Security.Cryptography.GostCmsSignature.Sign(ReadOnlySpan`1 dataHash, HashAlgorithmName hashAlgorithmName, X509Certificate2 certificate, AsymmetricAlgorithm key, Boolean silent, String& oid, ReadOnlyMemory`1& signatureValue)
         at LibCore.Security.Cryptography.Pkcs.Detours.CmsSignerDetour.Prefix(ReadOnlyMemory`1 data, String contentTypeOid, Boolean silent, X509Certificate2Collection& chainCerts, CmsSigner __instance, Object& __result)
         at System.Security.Cryptography.Pkcs.CmsSigner.Sign_Patch1(CmsSigner this, IntPtr retbuf, ReadOnlyMemory`1 data, String contentTypeOid, Boolean silent, X509Certificate2Collection& chainCerts)
         at System.Security.Cryptography.Pkcs.SignedCms.ComputeSignature(CmsSigner signer, Boolean silent)
         at System.Security.Cryptography.Pkcs.SignedCms.ComputeSignature(CmsSigner signer)
```

Воспроизводится как с Registry так и Directory вариантами размещения сертификатов.

Есть ли какие-то особенности регистрации или LocalMachine в принципе не поддерживается?

**Comment by Fasjeit** [comment]
Добрый день.

Для начала, на всякий случай, уточню - выданы ли права на закрытый ключ пользователю, от имени которого выполняется приложение?

**Comment by kae** [comment]
Да, приложение запускается под локальным администратором из elevated консоли.

Ну и старый вариант в .NET Framework 4.8 работает с тем же кодом, на этих же сертификатах, зарегистрированных в LocalMachine

**Comment by Fasjeit** [comment]
У себя пока не воспроизводим.

Если обратиться к свойству PrivateKey у сертификата ошибка будет аналогичной? Воспроизводится на любых сертификатах из LocalMachine?

Также попрошу вас уточнить версию csp.

**Comment by Fasjeit** [comment]
... а также уточнить имя контейнера ключа, если имеется кириллица - возможно, увы, всякое.

**Comment by kae** [comment]
CSP 5.0.12600

Console.WriteLine(signingCert.PrivateKey?.ToString());

выводит 

LibCore.Security.Cryptography.Gost3410_2012_256CryptoServiceProvider

Console.WriteLine(signingCert.PrivateKey?.SignatureAlgorithm);

выводит 

urn:ietf:params:xml:ns:cpxmlsec:algorithms:gostr34102012-gostr34112012-256

Как посмотреть имя контейнера ключа?
При размещении в варианте Directory сертификаты распологаются с путями
```
    Directory: C:\ProgramData\Crypto Pro\Crypto

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          20.04.2023    15:30                pfx-0cfc.000
d----          20.04.2023    15:15                pfx-52be.000
```

Пароль на контейнер не использовался.

Про "под любыми сертификатами" затрудняюсь ответить, но проверял на трёх разных.

**Comment by kae** [comment]
[Fl  Болохова Евгения 2023-11-04.zip](https://github.com/CryptoPro/libcore/files/11287750/Fl.2023-11-04.zip)
Да. Тестовый сертификат, выпущенный для тестирования. Пароль к pfx - "1"

Но на "полноценном" поведение было такое же.

**Comment by Fasjeit** [comment]
Попробуйте пожалуйста сборки из вложения:

[windows](https://file.cryptopro.ru/f/ZJsvr9qMPIafPDi9u4cNzBI6pzcAqRNU/LibCore.Windows.2023.4.24.1.nupkg)
[linux](https://file.cryptopro.ru/f/kh7JgoUX1cD67Ih6qKfoWBA4fGEEFr7A/LibCore.Linux.2023.4.24.1.nupkg)

**Comment by kae** [comment]
Проверил вариант для windows, проблема не воспроизводится.
