### ISSUE TITLE
LibCore при работе под Windows

### ISSUE THREAD

**Issue by k0st1x** [CryptoPro/libcore#16]
Здравствуйте, не получается завести библиотеку на Windows.
В проекте использую пакет LibCore.Windows.2023.4.25.1.
На машине, конечно же, стоит КриптоПро CSP 5 КС1.

Пробовал код [создания сертификата](https://github.com/CryptoPro/libcore#pfx-create), но, после ввода нажатий клавиш и движения мыши по окну "Био ДСЧ", библиотека падает с ошибкой
```
System.NotSupportedException: The certificate key algorithm is not supported.
   at LibCore.Internal.Cryptography.Pal.X509Pal.DecodePublicKey(Oid oid, Byte[] encodedKeyValue, Byte[] encodedParameters, ICertificatePal certificatePal)
   at LibCore.Internal.Cryptography.Pal.CertificateExtensionsCommon.GetPublicKey[T](X509Certificate2 certificate, Predicate`1 matchesConstraints)
   at LibCore.Security.Cryptography.X509Certificates.Gost3410CertificateExtensions.GetGost3410_2012_256PublicKey(X509Certificate2 certificate)
   at LibCore.Security.Cryptography.X509Certificates.Gost3410CertificateExtensions.CopyWithPrivateKey(X509Certificate2 certificate, Gost3410_2012_256 privateKey)
   at LibCore.Security.Cryptography.X509Certificates.CpCertificateRequest.CreateSelfSigned(DateTimeOffset notBefore, DateTimeOffset notAfter)
   at Program.<<Main>$>g__NewCertificateImpl|0_1(String subject)
   at Program.<<Main>$>g__NewCertificate|0_0(IEnumerable`1 arguments)\Program.cs:line 53
```

Так же пробовал код [загрузки из pfx](https://github.com/CryptoPro/libcore#file-pfx), но случается ошибка
```
LibCore.Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Bad Data.
   at LibCore.Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(Byte[] rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags)
   at LibCore.Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, CpX509KeyStorageFlags keyStorageFlags)
   at LibCore.Internal.Cryptography.Pal.CertificatePal.FromBlob(Byte[] rawData, SafePasswordHandle password, CpX509KeyStorageFlags keyStorageFlags)
   at LibCore.Security.Cryptography.X509Certificates.CpX509Certificate..ctor(Byte[] rawData, String password, CpX509KeyStorageFlags keyStorageFlags)
   at LibCore.Security.Cryptography.X509Certificates.X509CertificateExtensions.Create(Byte[] rawData, String password, CpX509KeyStorageFlags keyStorageFlags)
   at Program.<<Main>$>g__ExportPublicCertImpl|0_3(Byte[] certificateContent, String password)
```

Хотя тот же код под linux (LibCore.Linux.2023.4.25.1) работает без проблем.
Известная ли это проблема? Или для Windows надо использовать другой код/другие классы? Стоит ли создать проект с примером?

**Comment by Fasjeit** [comment]
День добрый. У нас пока что не воспроизводим, так что быстрее всего будет вам сделать проект, который на своей стороне проверим. Возможно где то странно работает флаг контейнеров, или передаёте не тот алгоритм.

Для загрузки из pfx также было бы отлично, если бы вы приложили и файл, который пытаетесь загрузить.

**Comment by k0st1x** [comment]
@Fasjeit про генерацию самоподписного сертификата. Похоже, что проблема у меня локальная, тк на другой Windows машине такого падения "System.NotSupportedException: The certificate key algorithm is not supported." не наблюдается.
Актуальна проблема только с загрузкой pfx

**Comment by Fasjeit** [comment]
Флаги `CpX509KeyStorageFlags.EphemeralKeySet | CpX509KeyStorageFlags.Exportable` выбраны осознанно? 

По идее флага `CpX509KeyStorageFlags.CspNoPersistKeySet` должно быть достаточно для работы с сертификатом. Если указать только его - ошибка воспроизводится?

**Comment by k0st1x** [comment]
@Fasjeit я не знаток в сертификатах, но следовал логике - мне нужно, чтобы сертификаты были inmemory, поэтому выставляю CspNoPersistKeySet;
В блогах по Windows Cryptographic видел заметку, что ОС может оставлять файлы сертификатов в файловой системе, чтобы этого небыло рекомендовали использовать флаг EphemeralKeySet.
Флаг Exportable я выставил, тк экспериментировал с .Export(X509ContentType.Cert).
С удовольствием воспользуюсь вашими знаниями по исползуемым флагам, если поделитесь.

Сейчас перегенерировал проект на использование только флага CspNoPersistKeySet и добился схожей ситуации - локально падает с исключением, а на соседней машине работает без ошибок.
Странно, но хоть так.
Проблему закрываю. @Fasjeit, спасибо за поддержку.

**Comment by Fasjeit** [comment]
`CspNoPersistKeySet` сам выставит `Exportable` (так как на самом деле указанные флаги не являются теми флагами, которые передаются в cryptoapi, почему то ms решили сделать так, мы в свою очередь эту логику не ломали), поэтому его выставлять не нужно.

Что касается EphemeralKeySet то он тут тоже не нужен, ибо эфемерные ключи работают в CSP чуть иначе, чем у ms, да и работа с контейнерами своя. Почему падает именно с ошибкой на пароле - хороший вопрос.

Для сценария загрузить сертификат, попользоваться его ключом, закрыть сертификат - достаточно и флага `CspNoPersistKeySet` (насколько нам известно). Также замечу, что контейнер ключа в данном случае не создаётся, поэтому действия связанные с установкой сертификата выполнить невозможно.

Если обнаружите какие то проблемы с флагами, которые вам нужны - пишите.
