### ISSUE TITLE
EnvelopedCms

### ISSUE THREAD

**Issue by Bykiev** [CryptoPro/libcore#17]
Здравствуйте, не подскажете хотя бы приблизительные сроки по реализации _EnvelopedCms_ в библиотеке?

**Comment by Fasjeit** [comment]
День добрый. В настоящий момент в работе, дорабатываем/тестируем.

По прогрессу по данному направлению напишу тут.

**Comment by Fasjeit** [comment]
Можно пробовать пререлизную сборку из вложения. Пока не очень стабильна, можно ожидать проблем.
[linux](https://file.cryptopro.ru/f/eLQXKTE7az8SRuKq9yt0jXRx6O9qaQN9/LibCore.Linux.2023.5.24.1.nupkg)
[win](https://file.cryptopro.ru/f/Ku7zAR57n2ZbCXyzbukCTNv5YUsDSCe1/LibCore.Windows.2023.5.24.1.nupkg)

Для cms шифрования нужно использовать класс `CpEnvelopedCms`, имеющий интерфейс исходного `EnvelopedCms`. Встраивание в исходный `EnvelopedCms` пока не делали.

**Comment by Bykiev** [comment]
Здравствуйте, протестировал на Windows и Linux (Astra Linux SE 1.7.3) все работает, спасибо!

**Comment by skuzminoff** [comment]
добрый день! попробовал использовать CpEnvelopedCms, в одну сторону (шифрование + кодирование) работает нормально, а вот в обратную сторону эксепшен на .Decode() 

```
LibCore.Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Invalid cryptograp
   at Internal.Cryptography.Pal.Windows.HelpersWindows.GetOriginatorCerts(SafeCryptMsgHandle hCryptMsg)
   at Internal.Cryptography.Pal.Windows.DecryptorPalWindows.Decode(Byte[] encodedMessage, Int32& version, ContentInfo& contentInfo, AlgorithmIdentifier& contentEncryptionAlgorithm, X509Certificate2Collection& originatorCerts, CpCryptographicAttributeObjectCollection& unprotectedAttributes)
   at Internal.Cryptography.Pal.Windows.PkcsPalWindows.Decode(Byte[] encodedMessage, Int32& version, ContentInfo& contentInfo, AlgorithmIdentifier& contentEncryptionAlgorithm, X509Certificate2Collection& originatorCerts, CpCryptographicAttributeObjectCollection& unprotectedAttributes)
   at LibCore.Security.Cryptography.CpEnvelopedCms.Decode(ReadOnlySpan`1 encodedMessage)
   at LibCore.Security.Cryptography.CpEnvelopedCms.Decode(Byte[] encodedMessage)
   at LibCore.TestApp.Cms.DecryptCms(Byte[] encryptedData, X509Certificate2 gostCert) in /app/LibCore.TestApp/Cms.cs:line 101
   at Program.<Main>$(String[] args) in /app/LibCore.TestApp/Program.cs:line 48
```

Версия LibCore - 2023.5.30.1
Версия csp - 5.0 R2
ОС -  debian 11

Сертификат получателя в хранлище my установлен.

**Comment by Fasjeit** [comment]
@skuzminoff добрый день.
Сможете приложить файл с проектом, сертификат с ключом, на котором пробуете расшифровать и сам зашифрованный файл?

**Comment by Fasjeit** [comment]
Пожалуйста, проверьте на ауктуальном релизе CSP (на данный момент это версия 5.0.12600), как указанно в Readme файле.

У себя локально на последнем релизе CSP не воспроизводим на вашем примере.

**Comment by skuzminoff** [comment]
@Fasjeit после обновления до 5.0.12800 пример стал падать на методе Encrypt() класса EnvelopedCms. Ошибка следующая
```
LibCore.Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: ASN1 bad tag
   at Internal.Cryptography.Pal.Windows.PkcsPalWindows.Encrypt(CmsRecipientCollection recipients, ContentInfo contentInfo, AlgorithmIdentifier contentEncryptionAlgorithm, X509Certificate2Collection originatorCerts, CpCryptographicAttributeObjectCollection unprotectedAttributes)
   at LibCore.Security.Cryptography.CpEnvelopedCms.Encrypt(CmsRecipientCollection recipients)
   at LibCore.Security.Cryptography.CpEnvelopedCms.Encrypt(CmsRecipient recipient)
   at LibCore.TestApp.Cms.EncryptCms(Byte[] dataToEncrypt, X509Certificate2 gostCert) in /app/Cms.cs:line 95
   at Program.<Main>$(String[] args) in /app/Program.cs:line 34
   ```

однако, прием с указанием ContentType у ContentInfo из вашего комментария (https://github.com/CryptoPro/corefx/issues/63#issuecomment-1366408025)  в соседнем репозитории помогает ошибки избежать, последовательности Encrypt->Encode  и Decode->Decrypt отработали с ожидаемым результатом.

**Comment by Fasjeit** [comment]
У 12800 поменялась логика в кодировании в EnvelopedCms, действительно возможны какие то наводки.
Как будет время - посмотрим. По результату отпишусь.

**Comment by skuzminoff** [comment]
@Fasjeit а где взять csp версии 5.0.12600? на сайте у вас доступна только версия 12800.

**Comment by Bykiev** [comment]
@Fasjeit, здравствуйте, не подскажете по срокам, когда будет решена эта проблема в последней сборке?

**Comment by Bykiev** [comment]
> Проблему воспроизвели, локализовали, ждём правок в csp.
> 
> Как только появится новая сборка которую можно посмотреть - отпишусь тут.
> 
> Отдельную под 12800 делать Libcore не хочется, ибо, скорее всего придётся потом откатить изменения с следующим релизом csp.

Спасибо, баг ведь влияет только на расшифровку, шифрование работает корректно в любой версии CSP?

**Comment by Fasjeit** [comment]
С 12800 проблема именно в шифровании, ибо csp не принимает передаваемый asn1 формат данных.

**Comment by Fasjeit** [comment]
В csp проблему починили, ждём релиза в ближайшие недели.

**Comment by Bykiev** [comment]
> В csp проблему починили, ждём релиза в ближайшие недели.

Здравствуйте, нет ли более точных сроков?

**Comment by maxdm** [comment]
Стараемся до конца июля

**Comment by maxdm** [comment]
Выложили: https://cryptopro.ru/products/csp/downloads#latest_csp50r3

**Comment by Fasjeit** [comment]
В релизе 12900 всё должно работать корректно.
