### ISSUE TITLE
Перестает работать LibCore

### ISSUE THREAD

**Issue by oleg-km** [CryptoPro/libcore#23]
Есть проект на ASP.NET Core 6. При запуске какое-то время все работало, но с утра перестало подписывать, кидает исключение:

Category: Microsoft.AspNetCore.Server.Kestrel
EventId: 13
SpanId: 687a1066b1349568
TraceId: 91222995c5c867862fed93f4081ae6f2
ParentId: 0000000000000000
ConnectionId: 0HMR0V4OGGGNF
RequestId: 0HMR0V4OGGGNF:00000002
RequestPath: /Crypto/Exec

Connection id "0HMR0V4OGGGNF", Request id "0HMR0V4OGGGNF:00000002": An unhandled exception was thrown by the application.

Exception: 
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Security.Cryptography.CryptographicException: Could not determine signature algorithm for the signer certificate.
   at System.Security.Cryptography.Pkcs.CmsSigner.Sign(ReadOnlyMemory`1 data, String contentTypeOid, Boolean silent, X509Certificate2Collection& chainCerts)
   at System.Security.Cryptography.Pkcs.SignedCms.ComputeSignature(CmsSigner signer, Boolean silent)
   at WebAGP2.Models.CryptoData.CmdSignData() in C:\_mnt\Disk0\Develop\work\WebAGP2\Models\CryptoData.cs:line 110
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at WebAGP2.Models.CryptoData.Exec(String cmd, String sessID) in C:\_mnt\Disk0\Develop\work\WebAGP2\Models\CryptoData.cs:line 63
   at WebAGP2.Controllers.CryptoController.Exec(String cmd, CryptoData data) in C:\_mnt\Disk0\Develop\work\WebAGP2\Controllers\CryptoController.cs:line 24
   at lambda_method39(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at WebAGP2.Program.<>c.<<Main>b__1_0>d.MoveNext() in C:\_mnt\Disk0\Develop\work\WebAGP2\Program.cs:line 28
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

Те я так понимаю, "отваливается" LibCore. Вопроса два: поможет ли повторная инициализация и что это и можно ли исправить?

**Comment by Bykiev** [comment]
Ошибка может возникать при неправильной цепочке сертификатов

**Comment by oleg-km** [comment]
Странно, он вчера этим сертификатом подписывал и все было нормально. И сейчас после перезагрузки тоже подписывает. Хорошо, проверим. Перед этим была ошибка про цепочки, Проверил под пользователем - цепочка есть, нормальная, отключил установкой флага в ЭЦП добавлять только конечный сертификат. А сегодня появилась эта ошибка. Помог перезапуск

**Comment by maxdm** [comment]
Попробуйте отключить Tiered compilation

31 мая 2023 г., в 12:38, Andrey Bykiev ***@***.***> написал(а):

﻿

Ошибка может возникать при неправильной цепочке сертификатов

**Comment by oleg-km** [comment]
Да, вроде помогла, пока не слетает
