### ISSUE TITLE
MailKit: System.IO.IOException: Cannot determine the frame size or a corrupted frame was received

### ISSUE THREAD

**Issue by Skit91** [CryptoPro/libcore#3]
Используя **ImapClient** из библиотеки **MailKit** (версия 3.4.3) возникает ошибка при вызове метода **ConnectAsync**:

System.IO.IOException: Cannot determine the frame size or a corrupted frame was received. at System.Net.Security.SslStream.GetFrameSize(ReadOnlySpan`1 buffer) at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter) at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer) at MailKit.Net.Imap.ImapStream.ReadAheadAsync(Int32 atleast, CancellationToken cancellationToken) at MailKit.Net.Imap.ImapStream.ReadTokenAsync(String specials, CancellationToken cancellationToken) at MailKit.Net.Imap.ImapEngine.ConnectAsync(ImapStream stream, Boolean doAsync, CancellationToken cancellationToken) at MailKit.Net.Imap.ImapClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
....

Шаги воспроизведения:

1. Подключаем библиотеку:
```
  var signed = new CmsSigner();
  LibCore.Initializer.Initialize();
```

2. Создаем подключение к почтовому ящику Яндекс:

```
    var protocolLogger = new ProtocolLogger(new MemoryStream());
    var client = new ImapClient(protocolLogger)
            {
                SslProtocols = SslProtocols.Tls,
                ServerCertificateValidationCallback = delegate { return true; }
            };

     await client.ConnectAsync("imap.yandex.ru", 993, true); // -- Ошибка здесь!
```

**Comment by Fasjeit** [comment]
Какая ос и версия csp?

**Comment by Skit91** [comment]
ОС: Astra Linux Orel 1.7.3
КриптоПРО: CSP (Type:80) v5.0.10008 KC1 Release Ver:5.0.12000 OS:Linux CPU:AMD64 FastCode:READY:AVX.

Воспроизводится и на Windows 10 Pro 19045.2364 БЕЗ установки КриптоПРО

**Comment by Fasjeit** [comment]
Без установленного CSP использование LibCore бессмысленно, ибо внутри используются вызовы к CSP.
Для корректной работы требуется версия CSP старше 5.0.12515 (в идеале последний актуальный релиз).

Попробуйте пожалуйста обновить CSP на астре и проверить, воспроизводится ли ошибка.

**Comment by Skit91** [comment]
Поставил: CSP (Type:80) v5.0.10011 KC1 Release Ver:5.0.12600 OS:Linux CPU:AMD64 FastCode:READY:AVX,AVX2.

Отвалилось подключение к БД Постгрес с аналогичной ошибкой:
- Microsoft.EntityFrameworkCore: 6.0.11
- Npgsql.EntityFrameworkCore.PostgreSQL:6.0.7
- PostgreSQL 14.5 (Ubuntu 14.5-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit


```
---> Npgsql.NpgsqlException (0x80004005): Exception while reading from stream
 ---> System.IO.IOException: Cannot determine the frame size or a corrupted frame was received.
   at LibCore.Net.Security.CpSslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at Npgsql.Internal.NpgsqlReadBuffer.<Ensure>g__EnsureLong|41_0(NpgsqlReadBuffer buffer, Int32 count, Boolean async, Boolean readingNotifications)
   at Npgsql.Internal.NpgsqlReadBuffer.<Ensure>g__EnsureLong|41_0(NpgsqlReadBuffer buffer, Int32 count, Boolean async, Boolean readingNotifications)
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|215_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.Internal.NpgsqlConnector.Authenticate(String username, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.Internal.NpgsqlConnector.<Open>g__OpenCore|195_1(NpgsqlConnector conn, SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)
   at Npgsql.Internal.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.OpenNewConnector(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.<Get>g__RentAsync|28_0(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<Open>g__OpenAsync|45_0(Boolean async, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
```

**Comment by Fasjeit** [comment]
Исходная ошибка с ImapClient всё ещё воспроизводится?

**Comment by Skit91** [comment]
С исходной ошибкой пока сложности, завтра постараюсь выделить время и сделать тестовый проект. Без использования инициализации LibCode исходный код успешно отрабатывает.

**Comment by Skit91** [comment]
Ошибка также воспроизводится на последней версии КриптоПРО.
Пример кода прикладываю:
[LibCode.SslTest.zip](https://github.com/CryptoPro/libcore/files/10486353/LibCode.SslTest.zip)

**Comment by Fasjeit** [comment]
Первая ошибка должна уйти. Пострес тоже лучше перепроверить.

win - https://file.cryptopro.ru/f/PePFsZwtF7rumm799U09eFCwZyQ75sIu/LibCore.Windows.2023.1.24.1.nupkg
linux - https://file.cryptopro.ru/f/UyDWLlwKdCaeT2Bg6IxAypkmKilQzsrB/LibCore.Linux.2023.1.24.1.nupkg

**Comment by Skit91** [comment]
ImapClient заработал.
Как с версией CryptoPro 12000 так и CryptoPro 12600.
Спасибо!

_PS/ Подключение к Пострес на версии 12600 не работает. Создам другое обращение для этого_
