### ISSUE TITLE
РЕД ОС 7.3.2 CryptographicException: The certificate chain is incomplete, the self-signed root authority could not be determined

### ISSUE THREAD

**Issue by Cyber-Watcher** [CryptoPro/libcore#30]
Добрый день!
Появилась другая ошибка.
Воодные данные по версии КриптоПро и либы те же что и были в этом issue https://github.com/CryptoPro/libcore/issues/28

При использовании утилиты командной строки КриптоПро csptest -keyset -check -cont '\\\\.\\HDIMAGE\\блаблабла
файл корректно подписывается. А при использовании библиотеки выдается следующая ошибка:

2023-08-03 16:41:55.950 [INF] CryptoSignerLinux:Sign - user System - message - This certificate HasPrivateKey = True
2023-08-03 16:42:26.118 [ERR] An unhandled exception has occurred while executing the request.
System.Security.Cryptography.CryptographicException: The certificate chain is incomplete, the self-signed root authority could not be determined.
at LibCore.Security.Cryptography.Pkcs.Detours.CmsSignerDetour.Prefix(ReadOnlyMemory1 data, String contentTypeOid, Boolean silent, X509Certificate2Collection& chainCerts, CmsSigner __instance, Object& __result) at System.Security.Cryptography.Pkcs.CmsSigner.Sign_Patch1(CmsSigner this, IntPtr retbuf, ReadOnlyMemory1 data, String contentTypeOid, Boolean silent, X509Certificate2Collection& chainCerts)
at System.Security.Cryptography.Pkcs.SignedCms.ComputeSignature(CmsSigner signer, Boolean silent)
at Vekas.CryptoSignerService.Business.CryptoSignerLinux.Sign(String text) in E:\TempGit\CryptoSigner_master_2023-08-01_14-19-46\Software\Vekas.CryptoSignerService\Business\CryptoSignerLinux.cs:line 79
at CryptoSignerService.Managers.CommandManager.SetCommand(BaseCSDto`1 apiCommand) in E:\TempGit\CryptoSigner_master_2023-08-01_14-19-46\Software\Vekas.CryptoSignerService\Managers\CommandManager.cs:line 64
at lambda_method2(Closure , Object , Object[] )

**Comment by Fasjeit** [comment]
Добрый день.

Жалуется на цепочку сертификата.

Ошибка только на Red Os воспроизводится?  Корневой сертификат установлен в хранилище и доступен?

**Comment by Cyber-Watcher** [comment]
Как я и говорил утилита командной строки 

cryptcp -sign -thumbprint bf7f8c1c57bdabbed9f4a68566893c61b9c38209 -detach -der "readme.txt" "readme.txt.sig" -nochain -norev

успешно подписывает файл.

Но, когда мы пытаемся использовать либу, то вылетает такая ошибка.

Как посмотреть установленные корневые сертификаты?

**Comment by Cyber-Watcher** [comment]
Спасибо большое! А где-то есть примеры использования консольной утилиты `certificate-tool` ?

**Comment by Fasjeit** [comment]
https://www.cryptopro.ru/sites/default/files/docs/certmgr.pdf
https://www.cryptopro.ru/faq/kak-v-linuxunix-ustanovit-sertifikaty

+ поиск по форуму https://www.cryptopro.ru/forum2/

**Comment by Cyber-Watcher** [comment]
Отелючил проверку цепочки сертификатов. Сделал как вы посоветовали. Полю IncludeOption задал значение None.
Теперь появилась другая ошибка, хотя как видно из логов подписание заработало, но все равно потом заваливается.

2023-08-04 14:55:11.301 [INF] CryptoSignerLinux:Sign - user System - message - This certificate HasPrivateKey = True
2023-08-04 14:55:11.437 [INF] CryptoSignerLinux:Sign - user System - message - CMS Sign: MIICOgYJKoZIhvcNAQcCoIICKzCCAicCAQExDDAKBggqhQMHAQECAjALBgkqhkiG9w0BBwExggIFMIICAQIBATCCAaAwggGJMR4wHAYJKoZIhvcNAQkBFg9jYUBza2Jrb250dXIucnUxGDAWBgUqhQNkARINMTAyNjYwNTYwNjYyMDEaMBgGCCqFAwOBAwEBEgwwMDY2NjMwMDMxMjcxCzAJBgNVBAYTAlJVMTMwMQYDVQQIDCo2NiDQodCy0LXRgNC00LvQvtCy0YHQutCw0Y8g0L7QsdC70LDRgdGC0YwxITAfBgNVBAcMGNCV0LrQsNGC0LXRgNC40L3QsdGD0YDQszFEMEIGA1UECQw70YPQu9C40YbQsCDQndCw0YDQvtC00L3QvtC5INCy0L7Qu9C4LCDRgdGC0YDQvtC10L3QuNC1IDE50JAxMDAuBgNVBAsMJ9Cj0LTQvtGB0YLQvtCy0LXRgNGP0Y7RidC40Lkg0YbQtdC90YLRgDEpMCcGA1UECgwg0JDQniAi0J/QpCAi0KHQmtCRINCa0L7QvdGC0YPRgCIxKTAnBgNVBAMMINCQ0J4gItCf0KQgItCh0JrQkSDQmtC+0L3RgtGD0YAiAhEDvEDiACOvEYdLzd4vGUVl5TAKBggqhQMHAQECAjAKBggqhQMHAQEBAQRAuD2WU/uJ57Cln23R6E05aFTNSfauNfw/FdeVcPowQ72bbC4lyslVybtnaN9T9IZ/dRcRZwHJhWQsaqCEICDShw==
2023-08-04 14:55:11.450 [ERR] An unhandled exception has occurred while executing the request.
System.Security.Cryptography.CryptographicException: Cannot find the original signer.
   at System.Security.Cryptography.Pkcs.SignerInfo.CheckSignature(X509Certificate2Collection extraStore, Boolean verifySignatureOnly)
   at System.Security.Cryptography.Pkcs.SignedCms.CheckSignatures(SignerInfoCollection signers, X509Certificate2Collection extraStore, Boolean verifySignatureOnly)
   at System.Security.Cryptography.Pkcs.SignedCms.CheckSignature(X509Certificate2Collection extraStore, Boolean verifySignatureOnly)
   at Vekas.CryptoSignerService.Business.CryptoSignerLinux.Sign(String text) in E:\TempGit\CryptoSigner_master_2023-08-04_14-02-27\Software\Vekas.CryptoSignerService\Business\CryptoSignerLinux.cs:line 84
   at CryptoSignerService.Managers.CommandManager.SetCommand(BaseCSDto`1 apiCommand) in E:\TempGit\CryptoSigner_master_2023-08-04_14-02-27\Software\Vekas.CryptoSignerService\Managers\CommandManager.cs:line 64
   at lambda_method2(Closure , Object , Object[] )

**Comment by Fasjeit** [comment]
Как я писал выше `None` отключает проверку цепочки и данная цепочка не включается в подписанное сообщение.

При проверке вы получаете ошибку, но невозможно найти подписанта. Если вы хотите проверять такое сообщение вам нужно явно указать сертификаты. Подробнее в документации на SignedCms.

https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.pkcs.signedcms.checksignature?view=windowsdesktop-7.0#system-security-cryptography-pkcs-signedcms-checksignature(system-security-cryptography-x509certificates-x509certificate2collection-system-boolean)

Отключать проверку цепочки я не советовал, лишь указал, как добиться поведения, которое вы наблюдаете при работе с утилитой. Использование `None` должно быть осознанным.

**Comment by Cyber-Watcher** [comment]
Спасибо. Просто у клиента нуль тарст сеть и пока они откроют нужные доступы проходят недели, если не месяца.  В общем на сколько я понял, с машины на которой работает наше ПО должен быть доступ к тем ресурсам в интернет, которые указаны в сертификате?

**Comment by Cyber-Watcher** [comment]
И можно еще что-то отключить в работе либы чтобы и эта ошибка не появлялась и подпись работала?

**Comment by yodasad** [comment]
@Cyber-Watcher , будет лучше, если Вы устраните проблему
```
The certificate chain is incomplete, the self-signed root authority could not be determined.
```
Установите корневой сертификат в доверенные корневые.

**Comment by Cyber-Watcher** [comment]
Установил сертификат командой `certmgr -inst -store uRoot -file skbkontur-q-2021.crt`, по выполении команды был код 0. То есть успешно как я понимаю. Но когда пытаюсь посмотреть его наличие в uRoot командой  `certmgr -list -store uRoot`, то его там нет. Что я делаю не так?

**Comment by yodasad** [comment]
Возможно, под разными пользователями запускаете команды (или, например, одну с sudo, другую без).
