### ISSUE TITLE
Ошибка LibCore.Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Provider could not perform the action since the context was acquired as silent.

### ISSUE THREAD

**Issue by KozlovPavel677** [CryptoPro/libcore#33]
Здравствуйте.

LibCore Выдает ошибку 
Description: The process was terminated due to an unhandled exception.
Exception Info: LibCore.Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Provider could not perform the action since the context was acquired as silent.
   at LibCore.Internal.NativeCrypto.CapiHelper.SignValue(SafeProvHandle hProv, SafeKeyHandle hKey, Int32 keyNumber, Int32 calgKey, Int32 calgHash, Byte[] hash)
   at LibCore.Security.Cryptography.Gost3410_2012_256CryptoServiceProvider.SignHash(Byte[] rgbHash)
   at LibCore.Security.Cryptography.Gost3410_2012_256CryptoServiceProvider.SignHash(Byte[] rgbHash, HashAlgorithmName hashAlgName)
   at LibCore.Security.Cryptography.Gost2012_256SignatureFormatter.CreateSignature(Byte[] rgbHash)
   at System.Security.Cryptography.AsymmetricSignatureFormatter.CreateSignature(HashAlgorithm hash)
   at System.Security.Cryptography.Xml.SignedXml.ComputeSignature_Patch1(SignedXml this)
   ...

В консольном приложении на net6 вызываем
SignedXml.ComputeSignature();
и оно вываливается с таким стеком.

Но при этом работает для другого сертификата. 
В чем может быть причина ?

**Comment by Bykiev** [comment]
Тестирование контейнера выполняется успешно в CSP? Такое может быть, если не был введен и запомнен пин-код

**Comment by Fasjeit** [comment]
Добрый день.

Как именно загружаете сертификат? Из pfx, из хранилища?

**Comment by KozlovPavel677** [comment]
> Как именно загружаете сертификат? Из pfx, из хранилища?

Добрый день.
Работает служба под доменной учеткой. Служба запускает консольное приложение, которое берет сертификат из хранилища личных сертификатов для учетки.
Сейчас проверю, что Пин-код введен и запомнен. Для другого юрлица (и, соответственно, другого сертификата) все работает.

**Comment by KozlovPavel677** [comment]
Для другого токена появилась такая ошибка.
Попросил админов запомнить там пароль, они попробовали, но к сожалению КриптоПро не выдал запрос на пароль, поэтому запомнить его не удалось.

Не подскажете почему такое возможно ?
Можно как-то самим впихнуть этот пароль в хранилище, миную КриптоПро ?
Или заставить крипто про задать этот вопрос.
