### ISSUE TITLE
Перестает работать отправка писем через System.Net.Mail

### ISSUE THREAD

**Issue by Buktop365** [CryptoPro/libcore#39]
Для отправки писем я пользуюсь стандартным System.Net.Mail. Там при отправке письма, если инициализировать LibCore через LibCore.Initializer.Initialize(Initializer.DetouredAssembly.NetSecurity), и даже если использовать сборки LibCore.Windiws.2023.9.26.1, то происходит ошибка:

System.NullReferenceException: Object reference not set to an instance of an object.
at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.TlsStreamAuthenticate()
at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.SendStartTlsCallback(IAsyncResult result)
--- End of stack trace from previous location ---
at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.End(IAsyncResult result)
at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)

Если не инициализировать вообще, или только с флагами Initializer.DetouredAssembly.Xml и Initializer.DetouredAssembly.Pkcs, то все работает как надо. Операционка - Windows 10, CSP - 5.0.12000 КС2

**Comment by Fasjeit** [comment]
На csp 5.0.12900 ошибка воспроизводится?

**Comment by Buktop365** [comment]
Пока попробовать нет возможности. В течение следующей недели попробую.
