### ISSUE TITLE
Ошибка при шифровании

### ISSUE THREAD

**Issue by ikhramtsov** [CryptoPro/libcore#72]
На windows получается зашифровать нормально,  когда ставим на VM "CentOS Linux 7 (Core)"
Container "Rocky Linux 8.5 (Green Obsidian)"
Выдает исключение:

System.DllNotFoundException: Unable to load shared library 'libcapi20' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/usr/lib64/dotnet/shared/Microsoft.NETCore.App/8.0.11/libcapi20.so: cannot open shared object file: No such file or directory
/app/libcapi20.so: cannot open shared object file: No such file or directory
/usr/lib64/dotnet/shared/Microsoft.NETCore.App/8.0.11/liblibcapi20.so: cannot open shared object file: No such file or directory
/app/liblibcapi20.so: cannot open shared object file: No such file or directory
/usr/lib64/dotnet/shared/Microsoft.NETCore.App/8.0.11/libcapi20: cannot open shared object file: No such file or directory
/app/libcapi20: cannot open shared object file: No such file or directory
/usr/lib64/dotnet/shared/Microsoft.NETCore.App/8.0.11/liblibcapi20: cannot open shared object file: No such file or directory
/app/liblibcapi20: cannot open shared object file: No such file or directory

   at Interop.Crypt32.CryptQueryObject(CertQueryObjectType dwObjectType, Void* pvObject, ExpectedContentTypeFlags dwExpectedContentTypeFlags, ExpectedFormatTypeFlags dwExpectedFormatTypeFlags, Int32 dwFlags, CertEncodingType& pdwMsgAndCertEncodingType, ContentType& pdwContentType, FormatType& pdwFormatType, SafeCertStoreHandle& phCertStore, SafeCryptMsgHandle& phMsg, SafeCertContextHandle& ppvContext)
   at CryptoPro.Security.Cryptography.X509Certificates.CertificatePal.FromBlobOrFile(ReadOnlySpan`1 rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at CryptoPro.Security.Cryptography.X509Certificates.CertificatePal.FromBlob(ReadOnlySpan`1 rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at CryptoPro.Security.Cryptography.X509Certificates.CpX509Certificate..ctor(ReadOnlySpan`1 data)
   at CryptoPro.Security.Cryptography.X509Certificates.CpX509Certificate..ctor(Byte[] data)
   at CryptoPro.Security.Cryptography.X509Certificates.CpX509Certificate2..ctor(Byte[] rawData)
   at CryptoProApi.Controllers.EncryptController.Encrypt(Data data) in /build/CryptoProApi/Controllers/EncryptController.cs:line 28
   at lambda_method1(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

**Comment by Fasjeit** [comment]
Не может найти библиотеку КриптоПро CSP (`liblibcapi20`), проверьте корректность установки CSP актуального релиза.
